# -*- coding: utf-8 -*-
"""Nhóm 12_Bài tập giữa kỳ 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7TnDF69ppl3mMkX-CBf23U18Y2FS40P

**Danh sách nhóm 12:**


*  K224060792_Nguyễn Thành Lợi
*  K224060795_Trần Như Cẩm Ly
*  K224060766_Trương Hoàng Anh

**CÂU 1: ĐƯA DATASET LÊN MONGODB, TRUY XUẤT DỮ LIỆU TỪ MONOGODB  LÊN JYPYTER NOTBOOK**
"""

!pip install requests pymongo
!pip install pandas

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://loint22406_db_user:175200@cluster175.qdjbnkk.mongodb.net/?appName=Cluster175"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# Re-using the URI that successfully connected in the previous cell
uri = "mongodb+srv://loint22406_db_user:175200@cluster175.qdjbnkk.mongodb.net/?appName=Cluster175"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Access the database named 'dtb'
db = client["dtb"]

# Access the collection named 'dtb'
collection = db["dtb"]

# Query the first 100 documents in the collection
documents = list(collection.find({}).limit(100))

# Print the retrieved documents
if documents:
    print(f"Found {len(documents)} documents in the 'dtb.dtb' collection:")
    for doc in documents:
        print(doc)
else:
    print("No documents found in the 'dtb.dtb' collection.")

"""Preview dữ liệu từ MongoDB"""

import pandas as pd

# Convert the list of documents to a Pandas DataFrame
df_documents = pd.DataFrame(documents)

# Display the DataFrame
display(df_documents)

"""**CÂU 2. VAEX XÂY DỰNG ỨNG DỤNG PHÂN TÍCH DATASET**"""

import pandas as pd
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://loint22406_db_user:175200@cluster175.qdjbnkk.mongodb.net/?appName=Cluster175"

client = MongoClient(uri, server_api=ServerApi('1'))
db = client["dtb"]
collection = db["dtb"]

documents = list(collection.find({}, {"_id": 0}))

df = pd.DataFrame(documents)
print(df.shape)
df.head()

df["Zipcode"] = df["Zipcode"].astype(str)
df.to_parquet("dtb_data.parquet")
print("✅ Đã xuất dữ liệu sang Parquet")

pip install vaex-core --no-build-isolation

import vaex

dfv = vaex.open("dtb_data.parquet")
dfv

"""Phân tích mức độ tai nạn - số lượng tai nạn theo mức độ nghiêm trọng"""

severity_stats = dfv.groupby("Severity", agg=vaex.agg.count())
severity_stats

"""Phân tích tai nạn theo thời gian (năm)"""

dfv['Start_Time'] = dfv['Start_Time'].astype('datetime64')
dfv['Year'] = dfv['Start_Time'].dt.year

accidents_per_year = dfv.groupby("Year", agg=vaex.agg.count()).sort("Year")
accidents_per_year

""" Phân tích ảnh hưởng ngày / đêm"""

day_night_stats = dfv.groupby("Sunrise_Sunset", agg=vaex.agg.count())
day_night_stats

"""Phân tích khoảng cách ảnh hưởng của tai nạn"""

dfv.mean(dfv["Distance(mi)"]), dfv.max(dfv["Distance(mi)"])

"""Phân tích vai trò của hạ tầng giao thông"""

# Tai nạn tại khu vực có đèn giao thông
traffic_signal_stats = dfv.groupby("Traffic_Signal", agg=vaex.agg.count())
traffic_signal_stats

# Tai nạn tại khu vực có biển Stop
stop_stats = dfv.groupby("Stop", agg=vaex.agg.count())
stop_stats

"""CÂU 3"""

!pip install streamlit pyngrok vaex pyarrow

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(page_title="US Accident Analytics", layout="wide")
# st.title("🚗 Phân tích Tai nạn Giao thông (Big Data)")
# 
# @st.cache_data
# def load_data():
#     df = pd.read_parquet("dtb_data.parquet")
#     df["Start_Time"] = pd.to_datetime(df["Start_Time"])
#     df["Year"] = df["Start_Time"].dt.year
#     return df
# 
# df = load_data()
# 
# # ===== METRICS =====
# col1, col2, col3 = st.columns(3)
# col1.metric("Tổng số tai nạn", f"{len(df):,}")
# col2.metric("Khoảng cách TB (mile)", round(df["Distance(mi)"].mean(), 3))
# col3.metric("Khoảng cách max (mile)", round(df["Distance(mi)"].max(), 3))
# 
# # ===== SEVERITY =====
# st.subheader("⚠️ Severity")
# severity = df.groupby("Severity").size()
# st.bar_chart(severity)
# 
# # ===== YEAR =====
# st.subheader("📅 Tai nạn theo năm")
# acc_year = df.groupby("Year").size().sort_index()
# st.line_chart(acc_year)
# 
# # ===== DAY / NIGHT =====
# st.subheader("🌞 Ngày / 🌙 Đêm")
# day_night = df.groupby("Sunrise_Sunset").size()
# st.bar_chart(day_night)
#

!streamlit run app.py

from pyngrok import ngrok
ngrok.connect(8501)

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok
ngrok.connect(8501)

"""4.1 Lấy token ngrok

Vào 👉 https://dashboard.ngrok.com

Copy Authtoken
390LK9yNoTnpgOAYuKiaaOp5z9C_714hb7PcgTQRvndfe4JzZ
"""

!pip install pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("390LK9yNoTnpgOAYuKiaaOp5z9C_714hb7PcgTQRvndfe4JzZ")
public_url = ngrok.connect(8501)
public_url

!pip install streamlit pyngrok vaex pyarrow

!ls

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &

!pkill streamlit

!nohup streamlit run app.py \
  --server.port 8501 \
  --server.address 0.0.0.0 \
  > streamlit.log 2>&1 &

!sleep 5
!curl http://127.0.0.1:8501

!sed -n '1,200p' streamlit.log

!ls -lh streamlit.log

!pip uninstall -y vaex vaex-core
!pip install vaex==4.16.0

!nohup streamlit run app.py \
  --server.port 8501 \
  --server.address 0.0.0.0 \
  > streamlit.log 2>&1 &

!sleep 5
!curl http://127.0.0.1:8501

!pip install pyngrok

!pip install streamlit pyngrok

!streamlit run app.py &>/content/logs.txt &



from pyngrok import ngrok

ngrok.set_auth_token("390LK9yNoTnpgOAYuKiaaOp5z9C_714hb7PcgTQRvndfe4JzZ")
public_url = ngrok.connect(8501)
public_url

"""Link thực thi: https://lowell-gastronomic-fae.ngrok-free.dev/

Link Github:
"""